"""Deterministic security rules for FAK Log Analyzer.

These rules intentionally use transparent thresholds rather than machine
learning. They are heuristics for triage and should not be interpreted as
proof that an attack occurred.
"""

# Authentication failures.
AUTH_FAILURE_MEDIUM_THRESHOLD = 5
AUTH_FAILURE_HIGH_THRESHOLD = 20

# 404 enumeration.
NOT_FOUND_MEDIUM_THRESHOLD = 10
NOT_FOUND_HIGH_THRESHOLD = 25
NOT_FOUND_DISTINCT_PATH_THRESHOLD = 5

# Requests generated by one IP within a single minute bucket.
REQUEST_BURST_MEDIUM_THRESHOLD = 60
REQUEST_BURST_HIGH_THRESHOLD = 120

# Access to paths commonly associated with configuration, administration,
# debugging, source-control metadata, or backup material.
SENSITIVE_PATHS = frozenset(
    {
        "/.env",
        "/.git/config",
        "/.htaccess",
        "/admin",
        "/administrator",
        "/config.php",
        "/debug",
        "/phpinfo.php",
        "/phpmyadmin",
        "/server-status",
        "/wp-admin",
        "/wp-login.php",
    }
)

SENSITIVE_PATH_PREFIXES = (
    "/.git/",
    "/backup/",
    "/backups/",
    "/config/",
    "/phpmyadmin/",
    "/wp-admin/",
)

SENSITIVE_PATH_MEDIUM_THRESHOLD = 1
SENSITIVE_PATH_HIGH_THRESHOLD = 3
